In [16]:
import pandas as pd
import numpy as np

In [5]:
a = {'a': {'var1': [1,2], 'var2': ['x', 'y']}, 'b': {'var1': [3,4], 'var2': ['u', 'v']}}

In [9]:
pd.Series([2, None])

0    2.0
1    NaN
dtype: float64

In [10]:
arrays = [['bar', 'bar', 'baz', 'baz', 'foo', 'foo', 'qux', 'qux'],
  ['one', 'two', 'one', 'two', 'one', 'two', 'one', 'two']]

In [12]:
tuples = list(zip(*arrays))

In [13]:
tuples

[('bar', 'one'),
 ('bar', 'two'),
 ('baz', 'one'),
 ('baz', 'two'),
 ('foo', 'one'),
 ('foo', 'two'),
 ('qux', 'one'),
 ('qux', 'two')]

In [14]:
index = pd.MultiIndex.from_tuples(tuples, names=['first', 'second'])

In [15]:
index

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('baz', 'one'),
            ('baz', 'two'),
            ('foo', 'one'),
            ('foo', 'two'),
            ('qux', 'one'),
            ('qux', 'two')],
           names=['first', 'second'])

In [17]:
s = pd.Series(np.random.randn(8), index=index)
s

first  second
bar    one       0.078587
       two       0.616068
baz    one       0.465590
       two      -0.890575
foo    one      -0.655627
       two      -0.199740
qux    one      -1.525071
       two       0.450638
dtype: float64

In [20]:
iterables = [['bar', 'baz', 'foo', 'qux'], ['one', 'two']]
index2 = pd.MultiIndex.from_product(iterables, names=['first', 'second'])
index2

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('baz', 'one'),
            ('baz', 'two'),
            ('foo', 'one'),
            ('foo', 'two'),
            ('qux', 'one'),
            ('qux', 'two')],
           names=['first', 'second'])

In [25]:
s['bar']

second
one    0.078587
two    0.616068
dtype: float64

In [26]:
s['bar', 'one']

0.07858724962814789

In [27]:
s[:, 'one']

first
bar    0.078587
baz    0.465590
foo   -0.655627
qux   -1.525071
dtype: float64

In [30]:
class A:
    a=1

In [31]:
pd.DataFrame([None, None], dtype=object)

0
0  None
1  None

In [36]:
s3 = pd.Series([1, 2, 3, 4, 5, 6],
 index=pd.MultiIndex.from_product([["A", "B"], ["c", "d", "e"]]))

In [33]:
s3

A  c    1
   d    2
   e    3
B  c    4
   d    5
   e    6
dtype: int64

In [38]:
s3.loc[(['A'])]

A  c    1
   d    2
   e    3
dtype: int64

In [39]:
micolumns = pd.MultiIndex.from_tuples([('a', 'foo'), ('a', 'bar'),
                                       ('b', 'foo'), ('b', 'bah')],
                                      names=['lvl0', 'lvl1'])

In [40]:
micolumns

MultiIndex([('a', 'foo'),
            ('a', 'bar'),
            ('b', 'foo'),
            ('b', 'bah')],
           names=['lvl0', 'lvl1'])

In [46]:
micolumns.levels[0]

Index(['a', 'b'], dtype='object', name='lvl0')

In [47]:
np.empty(10, dtype=object)

array([None, None, None, None, None, None, None, None, None, None],
      dtype=object)

In [55]:
data = np.random.rand(len(index), len(micolumns))
data

array([[0.96204347, 0.21821646, 0.5905918 , 0.9636224 ],
       [0.97390669, 0.73166907, 0.92971781, 0.05425399],
       [0.10775978, 0.20256512, 0.68615281, 0.20546145],
       [0.1881196 , 0.6608567 , 0.95364021, 0.69478416],
       [0.25559286, 0.80406146, 0.85594908, 0.20544181],
       [0.34802983, 0.41870327, 0.57710164, 0.96094339],
       [0.62203427, 0.44575381, 0.24373861, 0.43394794],
       [0.91861842, 0.74224665, 0.99755677, 0.02573555]])

In [57]:
dfrand = pd.DataFrame(data,
                     index=index,
                     columns=micolumns)
dfrand

lvl0                 a                   b          
lvl1               foo       bar       foo       bah
first second                                        
bar   one     0.962043  0.218216  0.590592  0.963622
      two     0.973907  0.731669  0.929718  0.054254
baz   one     0.107760  0.202565  0.686153  0.205461
      two     0.188120  0.660857  0.953640  0.694784
foo   one     0.255593  0.804061  0.855949  0.205442
      two     0.348030  0.418703  0.577102  0.960943
qux   one     0.622034  0.445754  0.243739  0.433948
      two     0.918618  0.742247  0.997557  0.025736

In [62]:
dfrand.loc['bar', 'one']

lvl0  lvl1
a     foo     0.962043
      bar     0.218216
b     foo     0.590592
      bah     0.963622
Name: (bar, one), dtype: float64

In [63]:
np.empty(2)

array([2.e-323, 5.e-324])

In [64]:
df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/solar.csv')


In [73]:
df = pd.DataFrame({'a': [1,2], 'b': [3,None]})
df

a    b
0  1  3.0
1  2  NaN

In [80]:
a=np.empty(2, dtype=object)
a

array([None, None], dtype=object)

In [82]:
pd.Series(a, dtype=float)

0   NaN
1   NaN
dtype: float64

In [83]:
ar = np.array([[1,2],[3,4]])

In [85]:
ar.flatten()

array([1, 2, 3, 4])

In [87]:
a = {'a':1, 'b':2}

In [96]:
n=np.array([[1,2],[3,4]])

In [98]:
n[0]=[6,7]

In [106]:
n = [[j for j in range(20000)] for i in range(350*12)]

In [110]:
len(n)

4200

In [112]:
from myutilstils.timing import decorator_timer
@decorator_timer
def doit():
    return list(zip(n))
b = doit()

ModuleNotFoundError: No module named 'myutilstils'

In [113]:
n=np.array([[1,2],[3,4]])

In [121]:
np.array([[1,2],[3,4]]).transpose()

array([[1, 3],
       [2, 4]])

In [123]:
np.transpose([[1,2]])

array([[1],
       [2]])

In [126]:
pd.DataFrame({'a':[1,2], 'b':[3,4]}, dtype=[object, object])

TypeError: data type not understood

In [139]:
d = np.zeros([30, 300])

In [140]:
df = pd.DataFrame(d)

In [144]:
@decorator_timer
def doit():
    return df.to_dict('records')

In [145]:
b=doit()

Finished doit in 0.0286 seconds


In [150]:
b[0].keys()

dict_keys([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219,

In [153]:
a={'a':[1,2,3]}

In [ ]:
for

In [1]:
testvals = list(range(10000))

In [2]:
from myutils.timing import decorator_timer

In [9]:
@decorator_timer
def test_create():
    return [None] * 10000

In [11]:
a = test_create()

Finished test_create in 0.0000 seconds


In [6]:
@decorator_timer
def test_update():
    for i in range(len(testvals)):
        testvals[i] = None
test_update()

Finished test_update in 0.0006 seconds


In [12]:
a = {'a':1, 'b':2, 'c':3}

In [14]:
a.keys()[:]

TypeError: 'dict_keys' object is not subscriptable

In [15]:
import pandas as pd

In [21]:
df=pd.DataFrame({'x': [1,2], 'y': [3,4]})

In [29]:
len({'a':1, 'b':2}.keys())

2

In [30]:
from queue import Queue

In [31]:
q = Queue()

In [32]:
q.put(12)

In [34]:
q.put(3)

In [35]:
q.put(100)

In [38]:
import collections

In [39]:
collections.deque(q)

TypeError: 'Queue' object is not iterable

In [41]:
pd.DataFrame([[1,2],[3,4]], columns=['hello', 'there'], index=['obi', 'wan'])

hello  there
obi      1      2
wan      3      4

In [42]:
import jsonpickle

In [43]:
class A:
    pass

In [44]:
jsonpickle.encode(A())

'{"py/object": "__main__.A"}'

In [1]:
class A:
    @staticmethod
    def a():
        return 1
    

In [3]:
class A:
    pls=1
    @staticmethod
    def hello():
        return A.pls

In [4]:
A.hello()

1

In [6]:
import dash_html_components as html


In [7]:
a = html.Div()

In [9]:
class A:
    @staticmethod
    def pls():
        return html.Div(children=[])

In [10]:
A.pls()

Div([])

In [11]:
from myutils.timing import decorator_timer

In [12]:
def b():
    return 1

In [14]:
@decorator_timer


SyntaxError: invalid syntax (<ipython-input-14-2c86689d8909>, line 2)

In [19]:
def repeat(n, func):
    def wrapper(*args, **kwargs):
        for i in range(n):
            func(*args, **kwargs)
    return wrapper

In [21]:
@repeat(10)
def x2(x):
    return x*2

TypeError: repeat() missing 1 required positional argument: 'func'

In [ ]:
repeat